# HW-playbook
---
- hosts: servers
  #  roles:
  #    - role: "RPM-based OS"
  #      when: ansible_facts['os_family'] == "RedHat"

  tasks:
  - name: "Update OS"
    become: true
    ansible.builtin.yum:
      name: '*'
      state: latest
      exclude: docker
      update_cache: true
    register: result

  - name: "reboot"
    become: true
    ansible.builtin.reboot:
      reboot_timeout: 360
      test_command: "whoami"
    when: result is changed

- hosts: local
  tasks:
    #  - name: "Update local OS"
    #    become: true
      #    ansible.builtin.yum:
      #      name: '*'
        #      state: latest
        #      exclude: docker
        #      update_cache: true
        #    register: result
      
      #  - name: "reboot local machine"
    #    become: true
      #    ansible.builtin.reboot:
      #      reboot_timeout: 240
        #      test_command: "whoami"
        #    when: result is changed

  - name: "delete old kernel-core"
    become: true
    ansible.builtin.yum:
      list: kernel-core
    register: result

...
